### ISSUE TITLE
Background image for one slide

### ISSUE THREAD

**Issue by statiksof** [jedcn/reveal-ck#104]
Hello! And thanks for opening up an issue!

Hi, it is not really an issue with reveal-ck. 
How can change background only for one slide and put an image. 
How to add side by side text like two columns. 
I am using markdown. 

I tried with html code but it did not work 

Thanks.

**Comment by jedcn** [comment]
Hey there! Sorry for taking to respond-- I presume you've moved on b/c you haven't asked anything else.

In short-- reveal-ck doesn't do anything that reveal.js doesn't do-- instead it just makes it easy to write the html that reveal.js expects.

You can write it in ruby, markdown, haml, slim, etc, etc.

If you're interested in backgrounds, you can see how adding a `data` attribute to a `<section>` element can give you background colors, images, etc over here:

https://github.com/hakimel/reveal.js/blob/master/demo.html#L191-L216

If you are writing slides in markdown you'll have to put the bare HTML into your markdown-- alongside the other parts of your slides.

If you're writing slides in haml or slim or erb or whatever you'd do the same and just follow the standards for those template languages.

As far as side-by-side text goes-- I'd recommend looking over at the official demo and if you see something there it's supported.. but if you don't see something you're on your own to experiment-- it should be possible-- it's just CSS and HTML after all-- but it might take too much energy.

Here's where I see something that might work for you (subject to change): https://revealjs.com/#/13

And here's the code for that part of the demo:

https://github.com/hakimel/reveal.js/blob/master/demo.html#L235-L240

I hope that helps and I hope you are well.

**Comment by statiksof** [comment]
@jedcn sorry for reopening this, I continued using the reveal-ck because I find it awesome framework. I am stuck again with the background issue. What do you mean by "_If you are writing slides in markdown you'll have to put the bare HTML into your markdown-- alongside the other parts of your slides._"?
I am using markdown and I tried to use this code for e.g.:

```
---

## Test

<section data-background="#dddddd" data-markdown>
Text 

</section>

---
```

but nothing changed. Can you help? Thank you.

**Comment by jedcn** [comment]
Hey there, @statiksof. No worries. Let me elaborate.. I need to remember how this works.

**Comment by jedcn** [comment]
Okay-- so the goal is to get a background color or a background image.

When we look at reveal.js, we know that this is achieved with a data attribute as described here:

https://revealjs.com/#/14

Where the exact example provided by the reveal.js demo is `data-background="#dddddd"`

Let's assume you are writing slides in markdown, and your `slides.md` contains the following content:

```md
Slide 1

---

Slide 2

---

Slide 3
```

When you run `reveal-ck generate` your slides will be generated in the `slides/` directory.

A helpful intermediate file to look at is `slides/slides.html`.

This file shows you what HTML the markdown in `slides.md` was translated into.

Here's what I see for HTML when I look at `slides/slides.html`:

```html
<section>

<p>Slide 1</p>

</section>
<section>

<p>Slide 2</p>

</section>
<section>

<p>Slide 3</p>

</section>
```

The contents from `slides/slides.html` are taken and copied into `slides/index.html` with a bunch of supporting reveal.js structure around it. This is the heart of your presentation. Right now it looks like three slides-- all without a background color.

Let's say we want to make the second slide have a background color.

The way we achieve this is to modify the `slides.md` so that it contains the second slide not as markdown but as HTML. We can get the HTML from the `slides/slides.html`.

Change `slides/slides.md` to this:

```md
Slide 1

---

<section data-background="#dddddd">

<p>Slide 2</p>

</section>

---

Slide 3

```

This merges markdown and HTML-- the first and third slides are in markdown and the second slide is in HTML.

The downside of the second slide being in HTML is that everything within it needs to be written within HTML. This can be mitigated if you write out what you want to have in markdown, generate the result, and then look into `slides/slides.html` and copy the generated HTML back into `slides.md`.

However, the upside of the second slide being in HTML is that you can supply the data attribute-- in this case now the second slide has a gray background.

Hope that helps.
