### ISSUE TITLE
GemDependencyError - reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard (~> 2.8)

### ISSUE THREAD

**Issue by azurewraith** [jedcn/reveal-ck#34]
Getting an odd dependency error on a fresh gem install... 

    [bcochran@lavos slides_ck]$ rbenv local 2.0.0-p451
    [bcochran@lavos slides_ck]$ gem install reveal-ck
    ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard (~> 2.8)
    [bcochran@lavos slides_ck]$ gem install reveal-ck -v '0.6.2'
    ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard (~> 2.8)
    [bcochran@lavos slides_ck]$ gem install reveal-ck -v '0.6.1'
    ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard (~> 2.8)
    [bcochran@lavos slides_ck]$ gem install reveal-ck -v '0.6.0'
    ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard  (~> 2.8)
    [bcochran@lavos slides_ck]$ gem install reveal-ck -v '0.5.0'
     Fetching: RedCloth-4.2.9.gem (100%)
     Building native extensions.  This could take a while...
     Successfully installed RedCloth-4.2.9
    ...
    Parsing documentation for minitest-5.5.1
    Installing ri documentation for minitest-5.5.1
    31 gems installed
    [bcochran@lavos slides_ck]$ ruby -v
    ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin13.4.0]

**Comment by jedcn** [comment]
Hey there, @azurewraith. I like your user name.

I see the same problem with 2.0.0:

```
slides ❯ rbenv local 2.0.0-p451 
slides ❯ ruby -v
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin14.0.0]
slides ❯ gem install reveal-ck
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard (~> 2.8)
```

Interestingly, it works for me with 2.1.2:

```
slides ❯ rbenv local 2.1.2
slides ❯ gem install reveal-ck
Fetching: reveal-ck-3.0.0.gem (100%)
Successfully installed reveal-ck-3.0.0
1 gem installed
```

With the immediate goal of getting you to the point where you can install, so that you are not completely blocked with reveal-ck, can you try with 2.1.x and let me know what you find?

**Comment by jedcn** [comment]
Hmm. I figured the travis-ci.org builds would be failing because they couldn't resolve this issue, either, but, they're not:

https://travis-ci.org/jedcn/reveal-ck/builds/52410915

**Comment by jedcn** [comment]
Hello again!

So-- two things are happening with this issue:

### First Thing

I'm locking all of the dependencies requested by reveal-ck to specific versions. This should eliminate the problem you reported where `gem` cannot resolve the ranges of `guard` and `guard-livereload` because there won't be any resolution to make.. it's just be whatever version we lock onto. See https://github.com/jedcn/reveal-ck/issues/35 for more details.

### Second Thing

I think the problem is in the version of `gem` that you're using. Can you update it?

I've got a workaround for you if you *cannot update your rubygems* and evidence that if you do update rubygems then things will work.

#### Bundler Workaround

While `gem` might get confused, `bundler` does not. As a workaround you can use `bundler` to help `gem` out. Previously I suggested that you try ruby 2.1.0, but the following will give you reveal-ck with ruby 2.0.0.

```sh
#
# Version Stuff
#
bundle-test ❯ ruby -v
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin14.0.0]
bundle-test ❯ gem -v
2.0.14
bundle-test ❯ bundle -v
Bundler version 1.8.3
#
# The problem!
#
bundle-test ❯ gem install reveal-ck
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard (~> 2.8)
#
# The Solution Part 1: Create a simple Gemfile
#
bundle-test ❯ echo "source 'https://rubygems.org'" > Gemfile
bundle-test ❯ echo "gem 'reveal-ck', '3.0.0'" >> Gemfile
bundle-test ❯ cat Gemfile
source 'https://rubygems.org'
gem 'reveal-ck', '3.0.0'
#
# The Solution Part 2: Bundle
#
bundle-test ❯ bundle
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Rubygems 2.0.14 is not threadsafe, so your gems must be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using rake 10.4.2
Using RedCloth 4.2.9
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using coderay 1.1.0
Using docile 1.1.5
Using eventmachine 1.0.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ffi 1.9.6
Using formatador 0.2.5
Using gemoji 1.5.0
Using gli 2.12.3
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.8.5
Using lumberjack 1.0.9
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using thor 0.19.1
Installing guard 2.6.1
Using multi_json 1.10.1
Installing guard-livereload 2.3.1
Using tilt 2.0.1
Using haml 4.0.6
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using html-pipeline 1.11.0
Using rack 1.6.0
Using rack-livereload 0.3.15
Using redcarpet 3.2.2
Using rinku 1.7.3
Using temple 0.6.10
Using slim 2.1.0
Installing reveal-ck 3.0.0
Using bundler 1.8.3
Bundle complete! 1 Gemfile dependency, 44 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
#
# Is it there?
#
bundle-test ❯ gem list | grep reveal-ck
reveal-ck (3.0.0)
#
# Does it work?
#
bundle-test ❯ reveal-ck -v
reveal-ck version 3.0.0
bundle-test ❯ echo "Hello World" > slides.md
bundle-test ❯ reveal-ck generate
Generating slides for 'slides.md'..
```

#### Gem Update

After getting the bundler workaround going above, I noticed that my rubygems was out of date. And so, I uninstalled both guard/guard-livereload and could reproduce again.

Then I did a system update of `gem` and the install worked:

```sh
#
# Uninstall guard/guard-livereload...
#
bundle-test ❯ gem uninstall guard

You have requested to uninstall the gem:
	guard-2.6.1

guard-livereload-2.3.1 depends on guard (~> 2.0)
rack-livereload-0.3.15 depends on guard (>= 0, development)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Remove executables:
	guard

in addition to the gem? [Yn]  Y
Removing guard
Successfully uninstalled guard-2.6.1
bundle-test ❯ gem uninstall guard-livereload
Successfully uninstalled guard-livereload-2.3.1
#
#  And verify that the problem still exists:
#
bundle-test ❯ gem install reveal-ck -v 3.0.0
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: reveal-ck requires guard (~> 2.6.1); guard-livereload requires guard (~> 2.8)
#
# Update Ruby Gems..
#
bundle-test ❯ gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.4.6.gem (100%)
Successfully installed rubygems-update-2.4.6
Installing RubyGems 2.4.6
RubyGems 2.4.6 installed

( ... Bug Fixes ... )

RubyGems installed the following executables:
	/opt/rubies/2.0.0-p451/bin/gem

RubyGems system software updated
bundle-test ❯ gem --version
2.4.6
#
# And see that it's fixed:
#
bundle-test ❯ gem install reveal-ck -v 3.0.0
Fetching: guard-2.6.1.gem (100%)
Successfully installed guard-2.6.1
Fetching: guard-livereload-2.3.1.gem (100%)
Successfully installed guard-livereload-2.3.1
Fetching: reveal-ck-3.0.0.gem (100%)
Successfully installed reveal-ck-3.0.0
3 gems installed
```

I haven't heard from you in about 3 weeks, so I presume you've moved on in one fashion or another. However-- if you are still interested in seeing this through, please comment on this issue and let me know how it went.

Best,

@jedcn

**Comment by tdarwin** [comment]
doing the gem update --system allowed me to do the install of reveal-ck without any issue. I'd been having the same problem as azurewraith.  thanks for the help.

regards,
@tdarwin

**Comment by azurewraith** [comment]
Thanks @jedcn for a thorough root cause and explanation.  In this instance I got the functionality I needed out of `0.5.0` but I will give it a go with an updated `gem` binary!

**Comment by jedcn** [comment]
Cool! I fixed the "First Thing" mentioned above by publishing 3.0.1: https://rubygems.org/gems/reveal-ck/versions/3.0.1. There's a chance that 3.0.1 will help because all versions are locked in place, and consequently, there's no opportunity for `gem` to get confused resolving stuff, so I'd hope that the following command works even with an old gem: `gem install reveal-ck -v 3.0.1`
