### ISSUE TITLE
How hard would it be to make reveal-ck generate a github-pages ready repo?

### ISSUE THREAD

**Issue by clee-jana** [jedcn/reveal-ck#38]

**Comment by jedcn** [comment]
Opps, I responded with a wall of text that I was intending to delete. Comment has been updated accordingly.

---

This shouldn't be too bad, right?

What can we assume?

* Can we assume that the person  that wants to do this is tracking content in git, already?
* Can we assume that they've got a repository created up on github.com, already?

Maybe it'd be better if we didn't assume any of that.

---

As I think about how this could get solved, I'm imagining a new command that was as peer to `generate` and `serve` and is named something like `publish` or `publish-to-gh-pages`.

My expected use case would be that someone would get reveal-ck installed and get the slides to a point where they wanted to share.

And then they'd run `reveal-ck publish-to-gh-pages` and be prompted with a series of questions that they'd answer.. and when done, their slides would be up on Github.

These questions could handle the fact that things weren't tracked in git yet, or that a remote didn't exist yet, and when answered would allow the user to have reveal-ck prompt them on what to do.

Is that along the lines of what you were thinking?

---

FYI: Here's a list of manual steps that's written up in the wiki if you're willing to take a bunch of manual steps: https://github.com/jedcn/reveal-ck/wiki/Publishing-Slides

**Comment by clee-jana** [comment]
Thanks, I'll check out the instructions and provide some feedback!

**Comment by bbesmanoff** [comment]
What may be nice to note is that prefacing [Step 1](https://github.com/jedcn/reveal-ck/wiki/Publishing-Slides#step-1-create-a-branch-named-gh-pages) with the `cd /tmp` will allow the branch that you create to be completely blank.  I attempted to perform the setup in my working directory and found that my slides were hosted under `/slides` instead of under the root.  While this can be useful, it may not always be expected.

For reference, the commands in my working directory were
```bash
reveal-ck generate
git checkout --orphan gh-pages
git rm -f .gitignore slides.md
git add .
git commit
```

**Comment by jedcn** [comment]
Hey there, @bbesmanoff! Good to hear from you. Thanks for taking the time to write in.

I've been in SF, else I would've responded earlier. I'll try to update the wiki as you say now. I think you have permissions to update the wiki, too? So-- if I lose your meaning in translation please let me know.

I re-read those instructions, and I was a bit lost at what I wrote :smile:. I am thinking I'd like to implement `reveal-ck publish-to-gh-pages` so that this algorithm can be written up in ruby and it'll be "hands off" for everyone else.

I just finished up a small javascript project, so, hopefully I'll make some time for reveal-ck soon. And clearly you're doing OK getting stuff up to `gh-pages` manually, so, that's good.

Hope you are well,

**Comment by kbrock** [comment]
Was looking into putting multiple slideshows into one directory.

Do you think it is most common to have one repo per talk?

Will see how far I can get for this feature

**Comment by jedcn** [comment]
You can have multiple "slide files" in a directory ala:

```
all-of-my-talks
├── talk-1.md
└── talk-2.md
```

And then generate slides into distinct directories with:

```
reveal-ck generate --file talk-1.md --dir talk-1
reveal-ck generate --file talk-2.md --dir talk-2
```

But I think most people do "one set of slides per repo."

If you do "one set of slides" then it's pretty clear what should be in the `gh-pages` branch: the generated slides for a single slides file.

**Comment by buren** [comment]
Something along the lines of
```
local gh_base_folder=slides
git subtree push --prefix $gh_base_folder origin gh-pages
```
could perhaps be used to push it to a `gh-pages` branch.

**Comment by kbrock** [comment]
I just created a slides folder with its own git repo pointing to gh-pages. Symbolically linked in a few directories.

I like your use of subtree. very cool.
I will test out subtree/modules and see where that gets me. thanks a lot.

**Comment by jedcn** [comment]
If you're still using reveal-ck and want a specific enhancement, please describe what you'd like and open it up. Cheers!
