### ISSUE TITLE
Background per slide in markdown

### ISSUE THREAD

**Issue by VinzentE** [jedcn/reveal-ck#63]
Hi there,

I love reveal-ck - amazing work, thank you for that!

I run into the following challenge at the moment: can I change the full screen background image for each slide? e.g. if I want to use mainly images within a presentation.

Was looking "everywhere" but couldn't find any solution really ...

Thanks for your help

**Comment by jedcn** [comment]
Hi! Thanks! You should be able to do it, but you need to use more than just
markdown. You need to use HTML.

You can put HTML snippets into markdown.. But if you're doing mainly images
you should consider switching to slides.html or html.erb or .slim or .haml.

I'm on mobile now-- I won't have my computer until tomorrow but I think you
want to make a section with a data-background attribute. The value should
be a URL leading to an image.. Either with a relative path or an absolute
one:

<section data-background="image.png">
Try this
</section>

More examples can be found with the reveal.js demo:

http://lab.hakim.se/reveal-js/#/10/1

Good luck! I will write again when I am back at a computer.

Hi there,

I love reveal-ck - amazing work, thank you for that!

I run into the following challenge at the moment: can I change the full
screen background image for each slide? e.g. if I want to use mainly images
within a presentation.

Was looking "everywhere" but couldn't find any solution really ...

Thanks for your help

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/jedcn/reveal-ck/issues/63>

**Comment by VinzentE** [comment]
Great - thanks a lot. I got it to work. Just added e.g. 
---

<section data-background="https://static.pexels.com/photos/71251/pexels-photo-71251.jpeg">
    <h2></h2>
</section>

---

within my markdown file.

Fantastic!

**Comment by VinzentE** [comment]
... trying out more things: one more question:

1. how to I add a fullscreen video (similar to a full screen image) - from local storage and from e.g. youtube?
2. how could I add e.g. animations via Gif (that ideally only plays once)?

Thanks again!

**Comment by jedcn** [comment]
Anything you can do in reveal.js should work in reveal-ck.

reveal-ck makes it easier to create reveal.js presentation by translating between markdown/html/whatever and generating a reveal.js presentation-- but it does not add slide functionality ontop of reveal.js.

So-- if you look here: https://github.com/hakimel/reveal.js#slide-backgrounds

You should see the authoritative source for what's possible with backgrounds.

For Question 1.: there's stuff for video at the above link.

For Question 2: Any background image that is also animated should be animated at full screen. I think you can generate a gif and make it only play once, but if a gif has been generated to loop that you have found on the internet I do not think you cannot easily stop it from looping.

For Question 3: See https://github.com/hakimel/reveal.js#pdf-export. I *think* it might work, but I have not tried it.

Best of luck!

**Comment by VinzentE** [comment]
Amazing! Thanks for that unbelievable fast response.

I think I got it now. Great! I totally love it!

Thanks again for your fantastic support.

**Comment by VinzentE** [comment]
Hi there,

sorry to ask again ... but I am facing two further challenges:

1. If I add a local image like this ![](_assets/myimage.png) => the html-presentation shows it as "missing file". I tried lots of different solutions, but I am just not getting it to work. In my html is looks like <img src="_assets/myimage.png" alt="">

2. can I somehow split up my presentation into several md-files? e.g. adding a 01_slides.md and so on so I make large presentations easier to handle? Live update feature should stay available ...

3. if I update one slide e.g. slide 12 then the full presentation reloads - which makes me having to navigate to slide 12 again to check the results. Any idea if I can set the reload to reload to the same position in the presentation?

Thanks for you help!
