### ISSUE TITLE
local images don't show

### ISSUE THREAD

**Issue by VinzentE** [jedcn/reveal-ck#65]
Hi there,

I am facing two further challenges:

1. If I add a local image like this  => the html-presentation shows it as "missing file". I tried lots of different solutions, but I am just not getting it to work. In my html is looks like 

2. can I somehow split up my presentation into several md-files? e.g. adding a 01_slides.md and so on so I make large presentations easier to handle? Live update feature should stay available ...

3. if I update one slide e.g. slide 12 then the full presentation reloads - which makes me having to navigate to slide 12 again to check the results. Any idea if I can set the reload to reload to the same position in the presentation?

Thanks for you help!

**Comment by jedcn** [comment]
Hi! I have a harder time responding during the work week-- I am better on weekends.

For #1, please check out this example: https://github.com/jedcn/reveal-ck/blob/master/features/generate-with-images.feature#L16-L23.

If you have a local image, you want to put it into a directory named `images/` and then it will be copied into a presentation and available to be referenced.

Are you committing your slides in Github and pushing them up? Or could you put them some place I could take a look? I might be able to troubleshoot.

For #2: There's been an issue open for awhile around that idea: https://github.com/jedcn/reveal-ck/issues/55. I will implement it shortly, but it's not possible now with markdown. Can you comment on issue #55 and say if the `contents_of` approach would work for you?

For #3-- My experience has been that so long as the slide number doesn't change you shouldn't lose your place. That is to say you shouldn't have to navigate 12 slides ahead each time. And even if the slide number changes because you added new ones-- you should only have to move ahead by one each time. Which browser are you using?

**Comment by jedcn** [comment]
Also-- I can't see the HTML that you're putting in. For example-- you have a sentence that reads: "In my html it looks like" but then I don't see anything.

I suspect you need to surround your html with triple backticks, so, do this:

    ```
      <p>Html</p>
    ```

**Comment by VinzentE** [comment]
Great.

to #1: working now - I think it would be great if it doesn't have to be "images" but can be called really anything - as long as the relativ path is correct.

to #2: contents_of would for sure work for me. Just tried it with a haml file "slides.haml" - but it only pulls in the "code" from the file, and is not processing the markdown. Is that feature already working or was that "work in progress"?

to #3: I have tried it with chrome and firefox. E.g. I have the text "test" on slide 3 (open parallel to my md-editor). Now when I update "test" to "test123" and hit save, it reloads my presentation in the browser but resets me back to slide 1. What I'd like to achieve is that is just reloads "slide 3" to show me the changes I have made.

For html snippets ... correct. Thanks!

**Comment by jedcn** [comment]
For 1: Glad to hear!

For 2: Right-- `contents_of` just brings in the content. What format is the "including" slide in? Are you writing a `slides.haml`? If you're using `.haml` or `.erb` you could write Ruby and involve [Tilt](https://github.com/rtomayko/tilt). Tilt would transform an including `.haml` file into HTML rather than bringing in the untranslated contents of the file. You might need an example-- I think there's a snippet at the end of the last comment in issue #55 that you could use as an example.

But-- your point is taken. I'll think about how you can include one type of file into another when in the future.

For 3. That's not how I remember it working, and that's a bummer for sure. I'll take a look shortly.

**Comment by jedcn** [comment]
This issue turned into a number of questions, and those were answered.

There are some problems-- such as whether or not the slide reloads to the correct page-- if those are problems and you want to re-open them specifically, I'll take a look.

Thanks!
