### ISSUE TITLE
fragment support for markdown

### ISSUE THREAD

**Issue by bertBruynooghe** [jedcn/reveal-ck#71]
I am currently creating a presentation which has a number of code snippets in html, slim and haml.
Since I don't want to resort to all kinds of escape tricks which render the presentation code base unmaintainable, I figured the best option would be to create the presentation using markdown.

However, I also need fragment support for some lists, so I figured I could do:

    <ul>
      <li class="fragment">...

But since I cannot intermingle, all subsequent markdown code is rendered wrongly. (Which is probaly as designed, as the [FAQ](https://github.com/jedcn/reveal-ck/wiki/FAQ#can-i-put-html-into-my-markdown)  seems to indicate.)

I also tried the following using kramdown syntax, but that also didn't work out:

    - {:.fragment} ...

Are there other options that could help me out here?

**Comment by bertBruynooghe** [comment]
One option that worked for me is:

- <div class="fragment">...</div>

**Comment by jedcn** [comment]
Thanks for writing up this request!

In order to do this in markdown, we need to come up with a syntactic extension to markdown that introduces the notion of "revealing" things.

For example, how do we distinguish between a regular list of three things and a list of three things that should be revealed/fade in as you advance?

Literally, here's an example:

Three items in a list (show all immediately):

```
* one
* two
* three
```

Three items in a list, hide each one initially and then reveal:

```
*> one
*> two
*> three
```

In this case, if something has a `>` it means it should be hidden initially.

But-- that doesn't make much sense to me and I can't think of a character (or set of characters) that intuitively means that things something should initially be hidden and then be revealed.

We could come up with a notation like `c.fragment` which, when present in an item, causes the `class="fragment"` to be attached to the associated node.

The general rule could be:

1. Convert everything from markdown to html.
2. Scan through the resulting html and look to see if `c.fragment` appears in a text node.
3. If so, remove `c.fragment` from the text but remember the element it was within and add `class="fragement"` as an attribute to that element.

This means you could write three list items that should have `class="fragment"` on them like:

```
* c.fragment one
* two c.fragment 
* c.fragment three
```

We could make a shorthand so that it doesn't distract as much from the actual text:

```
* c.f one
* two c.f
* c.f three
```

What do you think?

**Comment by bertBruynooghe** [comment]
I am a bit concerned that things are getting overly complicated: I thought that reveal-ck was just a construction kit for reveal.js to support a whole range of other languages, so it shouldn't introduce new syntax specific for markdown only. (It would also make documentation more difficult.)
For me, the issue would be solved if you simply use kramdown to  convert the markdown to html: that way the syntax `- {:.fragment} ...` would simply work, and you can refer to the kramdown and reveal.js documentation for this. (Btw, the reveal.js documentation shows something similar of you use the inline markdown feature.)

Also, the not-so-intuitive way of using `---` and `***` could then also be done by adding a class to the section divs, which would be far more intuitive for people that already know reveal.js, as the documentation there is quite complete.

As for my problem: I realized that `- <div class="fragment">...</div>` kind of solves my problems only partly: if the list items contain code snippets, I still have escape them manually.

I also considered using [middleman-presentation](https://github.com/fedux-org/middleman-presentation) instead (which kind of does similar things as reveal-ck), as that one already is using kramdown as parser AFAIK. OTOH,  its requirement of having nodejs installed, the bigger complexity, and the fact that we are already using reveal-ck at the office is making me stick with the good work you've done for reveal-ck. Maybe we can start looking for synergies between the two projects?

**Comment by jedcn** [comment]
Interesting. Do you mind me asking-- what company/office do you work at that already has momentum using reveal-ck?

reveal-ck does support several templating languages-- html (no template), haml, erb, slim, etc. My thinking has been that if people are knowledgable of reveal.js then they'll use one of these. It'll give you ultimate control over the html elements that appear in your presentation.

If you're using one those and you need to put code into your presentation things can surely get ugly when you mix proper code with an html templating language. So that's my thinking behind creating the `contents_of` function. It lets you store code separately and then include it. Here's [an example of using it in `haml`](https://github.com/jedcn/reveal-ck/blob/master/features/generate-using-contents_of.feature#L28-L33).

If you go this route, you can store your presentation in a file like `slides.html` or `slides.haml` and keep your code samples in distinct files like `code-example-1.rb` or `code-example-2.js`. Then you bring in those code files into your presentation with `contents_of`. A benefit here is that you can edit code in a distinct file and easily get syntax highlighting.. or even write tests for your code snippets.

That said-- if a user doesn't know reveal.js or they want to use a shorthand then that's when they'd use markdown. That's why I went to the idea of, "What is a new shorthand that could be introduced for markdown that'd make this easier for someone that's avoiding writing html itself?"

I'll take a look at kramdown. But for what it's worth markdown has several extensions already from what's describe [in the original markdown "spec"](http://daringfireball.net/projects/markdown/). Table support, emoji, @mentions, slide separators, and vertical slide separators.

Let me know if the `contents_of` route will help you.

I'll do some thinking.

**Comment by bertBruynooghe** [comment]
As to the 'momentum' of reveal-ck: we have a 'technical thursday' each month at the office, where some developpers present stuff. Until now, we have a few presentations made in reveal-ck, and a few developpers have been playing with it. So switching to some else would not directly help to increase adoption. (Common choice is still Google slides)

As to `contents_of`: that's a route I could go, but I prefer everything to be contained in one file, as to act as some kind of 'preview' of the slideset.

As to the extensions of markdown you already added: did you foresee means of escaping them?

**Comment by jedcn** [comment]
I looked around at kramdown and you'd get what you wanted if reveal-ck explicitly supported kramdown.

My proposal then is that I'll publish a new version of reveal-ck that will allow you to create a file named `slides.kramdown`. This file will be parsed with [kramdown][kramdown] itself and so you'll be able to put any valid kramdown in there.

If we take this approach, it'll be tantamount to saying, "reveal-ck works with many templating languages, kramdown is a templating language, and so, reveal-ck will work with yet one more language."

In this case, kramdown fans like yourself will get exactly what they want: legitimate kramdown support for building slides. Logically, reveal-ck will continue to build out reveal.js presentations-- you'll just have another "language" to create those slide presentations in.

What do you think? Do you agree that this will solve your problems and that having the markdown parser of your choosing will be what you need?

[kramdown]: https://github.com/gettalong/kramdown

**Comment by bertBruynooghe** [comment]
sounds perfect!

**Comment by kbrock** [comment]
There have been a number of extensions (or requests) across markdown implementations to add a css class/id to a block.

Haven't looked at common mark recently, but maybe it has come across a solution.

**Comment by jedcn** [comment]
Cool. Thanks @kbrock. Also @bertBruynooghe-- I'll take a look at replacing the core engine for markdown ([redcarpet](https://github.com/vmg/redcarpet)) with kramdown while I'm in there-- the current engine was selected for its processing hooks (pre, post, per-block).

**Comment by jedcn** [comment]
Unless I'm missing something about kramdown, making it process files ending in `kramdown` such as an explicit `slides.kramdown` won't give you what you're looking for. See the associated PR commits for details.

I'll look into swapping out `redcarpet` with `kramdown` next.

**Comment by bertBruynooghe** [comment]
I agree with you it's not going to work for using `<section>`, but the `* {:.fragment} ...` syntax seems like it should work, unless I'm badly mistaken.

I was also thinking about a way to start using nested lists in markdown with some  [attribute list definition](http://kramdown.gettalong.org/syntax.html#attribute-list-definitions) attached  to mimic the 'nestedness' of the sections concept in reveal-ck itself, but that doesn't seem feasible, and maybe not a good idea neither.

**Comment by jedcn** [comment]
Good news on the kramdown front!

I got `slides.kramdown` working as you'd expect. You can use `---` to separate slides and write kramdown everywhere else. The `{:.fragment}` is working for ordered and unordered list items and it's actually pretty slick.

I noticed that kramdown isn't producing code blocks the way reveal.js expects. I'll take a look at that.

Also-- @bertBruynooghe are there any other things you'd like to put a `class="fragment` on? Or ways you'd like to use kramdown to impact the produced markup? If you speak up now I'll take a look before I cut a release.

Also-- if the main reason you want kramdown is for `{:.fragment}` support I might be able to support *just that* back in the world of regular markdown / `slides.md`.

**Comment by bertBruynooghe** [comment]
Hi, thanks for all the great work so far!

Unfortunately, for me the biggest thing would indeed be having fragments with code blocks inside them (see [example](https://gitlab.com/BertBruynooghe/lean_html_in_a_rails_context_presentation/raw/master/slides.md) ), so apparently kramdown doesn't cut it.

I have been looking into ways to get around the code blocks issue using kramdown itself, but I don't see any direct solution there.
So I guess the cleanest thing would probably be to add something like [attribute list definitions](http://kramdown.gettalong.org/syntax.html#attribute-list-definitions) in the world of regular markdown. (That would also make <code>``` {:.notes}</code> consistent with the rest of the ideas, and maybe have some upwards compatibity with future new features of reveal.js itself.)

I also found [extra markdown](https://michelf.ca/projects/php-markdown/extra/#spe-attr) is using the same syntax, and reveal.js also has a similar syntax.

I might also open a ticket on kramdown itself, so they might adapt their  <code>```</code> implementation to match common mark, so that would be  a fix also.

**Comment by jedcn** [comment]
Hmm. Ok. Your example is running into a 404 for me. Can you please double-check it?

I'm off to work for the day, I'll check back later, but if you can clarify the example that'd be great.

**Comment by bertBruynooghe** [comment]
mmm, apparently you can't access my [gitlab example](https://gitlab.com/BertBruynooghe/lean_html_in_a_rails_context_presentation/raw/master/slides.md) without being logged in to gitlab. 

So I copied the file in a [gist here](https://gist.githubusercontent.com/bertBruynooghe/216bb65094cdecb50b6ac626de36cd22/raw/1ece73218e8d6aa6ede989f69a9ef70f77d714ea/slides.md).

**Comment by gettalong** [comment]
@bertBruynooghe I looked at your gist. If you want to use kramdown make sure that you use empty lines between block level elements.

So if you change from this

~~~
***
## HTML Templating Languages
---
### HTML.erb
    <p id="notice"><%= notice %></p>
    <p><strong> Name: </strong><%= @insulin.name %></p>
    <%= link_to 'Edit', edit_insulin_path(@insulin) %>
    |
    <%= link_to 'Back', insulins_path %>
---
### HAML
    %p#notice
      = notice
    %p
      %strong Name:
      = @insulin.name
    = link_to 'Edit', edit_insulin_path(@insulin)
    '|
    = link_to 'Back', insulins_path
---
### HAML
* <div class="fragment"> More concise than HTML </div>
* <div class="fragment"> Online conversion to/from HTML </div>
~~~

to this:

~~~
***

## HTML Templating Languages

---

### HTML.erb

    <p id="notice"><%= notice %></p>
    <p><strong> Name: </strong><%= @insulin.name %></p>
    <%= link_to 'Edit', edit_insulin_path(@insulin) %>
    |
    <%= link_to 'Back', insulins_path %>

---

### HAML

    %p#notice
      = notice
    %p
      %strong Name:
      = @insulin.name
    = link_to 'Edit', edit_insulin_path(@insulin)
    '|
    = link_to 'Back', insulins_path

---

### HAML

* {:.fragment} More concise than HTML
* {:.fragment} Online conversion to/from HTML
~~~

it should work fine (depending on what the kramdown integration does to the file itself).

**Comment by bertBruynooghe** [comment]
@gettalong Thanks for the help; the example I gave is currently still rendered using redcarpet. It is meant as an example on what I had to do to get it working today. The idea would be that if we had the attribute list definitions in place, and the code blocks are rendered correctly, it would take less escaping to do in  the codeblocks that are inside the list items acting as a fragment.

**Comment by bertBruynooghe** [comment]
@jedcn 

After some help from @gettalong , it was found that following syntax in kramdown does render to `<pre><code></code></pre>`:

    ~~~
    some code
    ~~~

So that would make my example way simpler if kramdown is supported.

**Comment by jedcn** [comment]
kramdown is now the markdown processor for any file ending in `.md`. It's really quite slick. I was not aware of the project-- thank you for your suggestion!

I added [features](https://github.com/jedcn/reveal-ck/blob/master/features/generate-with-markdown.feature#L409-L481) that describe the basis of what I've verified works as expected.

Version 3.4.0 has been published here (https://rubygems.org/gems/reveal-ck/versions/3.4.0) if you'd like to try it out.

ps: To follow up in this thread-- you can use triple backticks for code:

    ```
    some code
    ```
