### ISSUE TITLE
Upgrading to the latest reveal.js

### ISSUE THREAD

**Issue by rastamhadi** [jedcn/reveal-ck#84]
I was looking into upgrading my slides to the latest version of reveal.js, but it looks like the only way to do this is to change the git submodule inside the gem, which is currently fixed at version 3.0.0. Am I right in assuming that you only intend to upgrade with each major release? I can see how keeping up with every minor release would be a pain to maintain. 😅

**Comment by jedcn** [comment]
Hey there, @rastamhadi! Thanks for opening an issue.

I was originally thinking that I'd upgrade it with major versions.. and then every so often.

It's been awhile since an upgrade so it seems like now might be a good time-- can you give me some insight about what features/aspects you're looking for?

I'm asking because I want to make sure the upgraded result captures the functionality that you want.

**Comment by rastamhadi** [comment]
Oh wow! Didn't expect a response so soon 😄 

I wanted the Speaker Notes keyboard shortcut to show up in the help overlay (the one that toggles when you hit `?` on the keyboard).

![_slack_ _](https://user-images.githubusercontent.com/1012322/26859743-d8d06250-4b74-11e7-956e-6bf7e74e8c94.png)

**Comment by jedcn** [comment]
A new version of reveal-ck, version 3.7.0, has the latest released+tagged version of reveal.js (version 3.5):

https://rubygems.org/gems/reveal-ck/versions/3.7.0

**Comment by jedcn** [comment]
Hope this helps! Let me know if it does not do what you wanted.

**Comment by rastamhadi** [comment]
I ran `bundle update` and regenerated my slides.
It does exactly what I wanted as far as I can see.
Thank you very much! ❤️
